# -*- coding: utf-8 -*-
"""NLP-LAB-5-Program

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zy5fl-jvF-5cOIkWwFumIzivjb5im9Mv

LAB-5
"""

import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt') # Ensure 'punkt_tab' tokenizer is downloaded
nltk.download('punkt_tab') # Download the 'punkt_tab' resource
nltk.download('averaged_perceptron_tagger_eng') # Download the POS tagger
text = word_tokenize("And now for something completely different")
tags = nltk.pos_tag(text)
print(tags)

import nltk
nltk.download('brown')
text = nltk.Text(word.lower() for word in nltk.corpus.brown.words())
text.similar('woman')
text.similar('bought')
text.similar('over')
text.similar('the')

""" Tagged Corpora

"""

tagged_token = nltk.tag.str2tuple('fly/NN')
print(tagged_token)
print(tagged_token[0])
print(tagged_token[1])

import nltk
sent ="""
The/AT grand/JJ jury/NN commented/VBD on/IN a/AT number/NN of/IN
other/AP topics/NNS,/, AMONG/IN them/PPO the/AT Atlanta/NP and/CC
Fulton/NP-tl County/NN-tl purchasing/VBG departments/NNS which/WDT it/PPS
said/VBD/ ARE/BER well/QL operated/VBN and/CC follow/VB generally/RB
accepted/VBN practices/NNS which/WDT inure/VB to/IN the/AT best/JJT
interest/NN of/IN both/ABX governments/NNS ''/"."""
tagged_tokens = [nltk.tag.str2tuple(t) for t in sent.split()]
print(tagged_tokens)

import nltk
nltk.download('universal_tagset') # Download the universal tagset
# Using the default Brown corpus tagset
tagged_words_default = nltk.corpus.brown.tagged_words()
print(tagged_words_default)
# Using the Universal Tagset for the Brown corpus
tagged_words_universal = nltk.corpus.brown.tagged_words(tagset='universal')
print(tagged_words_universal)

import nltk
nltk.download('nps_chat')
nltk.download('conll2000')
nltk.download('treebank')
# Access tagged words from the NPS Chat corpus
nps_chat_tagged_words = nltk.corpus.nps_chat.tagged_words()
print(nps_chat_tagged_words)
# Access tagged words from the CoNLL 2000 corpus
con112000_tagged_words = nltk.corpus.conll2000.tagged_words()
print(con112000_tagged_words)
# Access tagged words from the Treebank corpus
treebank_tagged_words = nltk.corpus.treebank.tagged_words()
print(treebank_tagged_words)

import nltk
# Access tagged words from the Brown corpus with the Universal Tagset
brown_tagged_words_universal = nltk.corpus.brown.tagged_words(tagset='universal')
print(brown_tagged_words_universal)
# Access tagged words from the Treebank corpus with the Universal Tagset
treebank_tagged_words_universal = nltk.corpus.treebank.tagged_words (tagset='universal')
print(treebank_tagged_words_universal)

import nltk
nltk.download('sinica_treebank')
nltk.download('indian')
nltk.download('mac_morpho')
nltk.download('conll2002') # Corrected from conl12002
nltk.download('cess_cat')
# Access tagged words from the Sinica Treebank corpus
sinica_treebank_tagged_words = nltk.corpus.sinica_treebank.tagged_words()
print(sinica_treebank_tagged_words)
# Access tagged words from the Indian corpus
indian_tagged_words = nltk.corpus.indian.tagged_words()
print(indian_tagged_words)
# Access tagged words from the Mac-Morpho corpus
mac_morpho_tagged_words = nltk.corpus.mac_morpho.tagged_words()
print(mac_morpho_tagged_words)
# Access tagged words from the CoNLL 2002 corpus
con112002_tagged_words = nltk.corpus.conll2002.tagged_words()
print(con112002_tagged_words)
# Access tagged words from the CESS-CAT corpus
cess_cat_tagged_words = nltk.corpus.cess_cat.tagged_words()
print(cess_cat_tagged_words)

from nltk.corpus import brown
brown_news_tagged = brown.tagged_words (categories='news', tagset='universal')
tag_fd = nltk.FreqDist(tag for (word, tag) in brown_news_tagged)
tag_fd.most_common()

# Load the Brown corpus and filter it to use only the 'news' category
brown_news_tagged = nltk.corpus.brown.tagged_words (categories='news')
# Generate bigrams from the tagged words in the 'news' category
word_tag_pairs = nltk.bigrams (brown_news_tagged)
# Filter for cases where the second item in the bigram is tagged as a noun ('NOUN')
noun_preceders = [a[1] for (a, b) in word_tag_pairs if b[1] == 'NOUN']
# Create a frequency distribution of the tags that precede nouns
fdist = nltk.FreqDist(noun_preceders)
# Extract the most common tags that precede nouns
most_common_tags = [tag for (tag, _) in fdist.most_common()]
print (most_common_tags)

import nltk
# Access tagged words from the Treebank corpus with the Universal Tagset
wsj = nltk.corpus.treebank.tagged_words (tagset='universal')
# Create a frequency distribution of word-tag pairs
word_tag_fd = nltk.FreqDist(wsj)
# Extract the most common words tagged as verbs
verbs = [wt[0] for (wt, _) in word_tag_fd.most_common() if wt[1] == 'VERB']
print(verbs)

import nltk

# Assuming 'wsj' contains the Wall Street Journal portion of the Treebank corpus
# If 'wsj' is not defined yet, load the Wall Street Journal portion of the Treebank corpus
wsj = nltk.corpus.treebank.tagged_words()
# Create a ConditionalFreqDist object
cfd1 = nltk.ConditionalFreqDist(wsj)
# Check the distribution of parts of speech for the word 'yield'
yield_pos_distribution = cfd1['yield'].most_common()
print("Distribution of 'yield':", yield_pos_distribution)
# Check the distribution of parts of speech for the word
cut_pos_distribution = cfd1['cut'].most_common()
print("Distribution of 'cut':", cut_pos_distribution)

import nltk
# Assuming 'wsj' contains the Wall Street Journal portion of the Treebank corpus
# If 'wsj' is not defined yet, load the Wall Street Journal portion of the Treebank corpus
wsj = nltk.corpus.treebank.tagged_words()
# Create a ConditionalFreqDist object by swapping word and tag positions
cfd2 = nltk.ConditionalFreqDist((tag, word) for (word, tag) in wsj)
# List words tagged as 'VBN' (past participle)
vbn_words = list(cfd2['VBN'])
print(vbn_words[:20]) # Display the first 20 words for brevity

import nltk
# Assuming 'wsj' contains the Wall Street Journal portion of the Treebank corpus
# If 'wsj' is not defined yet, load the Wall Street Journal portion of the Treebank corpus
wsj = nltk.corpus.treebank.tagged_words()
# Create a ConditionalFreqDist object 'cfd1'
cfd1 = nltk.ConditionalFreqDist((word, tag) for (word, tag) in wsj)
# Find words that are tagged as both 'VBD' (past tense) and 'VBN' (past participle)
words_with_vbd_and_vbn = [w for w in cfd1.conditions() if 'VBD' in cfd1[w] and 'VBN' in cfd1[w]]
print(words_with_vbd_and_vbn[:10]) # Display the first 10 words for brevity
# Find context surrounding 'kicked' as 'VBD'
idx1 = wsj.index(('kicked', 'VBD'))
print(wsj[idx1-4:idx1+1])
# Find context surrounding 'kicked' as 'VBN'
idx2 = wsj.index(('kicked', 'VBN'))
print(wsj[idx2-4:idx2+1])

import nltk
def findtags (tag_prefix, tagged_text):
    cfd = nltk.ConditionalFreqDist((tag, word) for (word, tag) in tagged_text
                                   if tag.startswith(tag_prefix))
    return {tag: cfd[tag].most_common(5) for tag in cfd.conditions()}
tagged_news = nltk.corpus.brown.tagged_words (categories='news')
tagdict = findtags('NN', tagged_news)
for tag in sorted(tagdict):
    print(tag, tagdict[tag])

import nltk
# Assuming 'brown_learned_text' contains the words from the 'learned' category of the Brown corpus
brown_learned_text = nltk.corpus.brown.words (categories='learned')
# Find words that occur after 'often' in the 'learned' category of the Brown corpus
words_after_often = sorted(set(b for (a, b) in nltk.bigrams (brown_learned_text) if a == 'often'))
print(words_after_often)

brown_lrnd_tagged = brown.tagged_words(categories='learned', tagset='universal')
tags = [b[1] for (a, b) in nltk.bigrams(brown_lrnd_tagged) if a[0] == 'often']
fd = nltk.FreqDist(tags)
fd.tabulate()

from nltk.corpus import brown
import nltk
def process (sentence):
    for (w1, t1), (w2, t2), (w3, t3) in nltk.trigrams(sentence):
        if t1.startswith('V') and t2 == 'TO' and t3.startswith('V'):
            print(w1, w2, w3)
# Iterate through tagged sentences in the Brown corpus and apply the 'process' function
for tagged_sent in brown.tagged_sents():
    process (tagged_sent)

from nltk.corpus import brown
import nltk
# Extract tagged words from the 'news' category of the Brown corpus using the Universal Tagset
brown_news_tagged = brown.tagged_words (categories='news', tagset='universal')
# Create a ConditionalFreqDist object based on the tagged words
data = nltk.ConditionalFreqDist((word.lower(), tag) for (word, tag) in brown_news_tagged)
# Iterate through words in sorted order and print words with more than three different tags
for word in sorted(data.conditions()):
    if len(data[word]) > 3:
        tags = [tag for (tag, _) in data[word].most_common()]
        print(word,''.join(tags))

pos = {} # Creating an empty dictionary named 'pos'
pos['colorless'] = 'ADJ' # Adding 'colorless' with the tag 'ADJ' to the dictionary
pos['ideas'] = 'N' # Adding 'ideas' with the tag 'N' to the dictionary
pos['sleep'] = 'V' # Adding 'sleep' with the tag 'V' to the dictionary
pos['furiously'] = 'ADV' # Adding 'furiously' with the tag 'ADV' to the dictionary
pos

pos['ideas']

pos['colorless']

list(pos) # [1]
sorted(pos) # [2]
[w for w in pos if w.endswith('s')]

for word in sorted(pos):
    print(word + ":", pos [word])

pos = {
'colorless': 'ADJ',
'ideas': 'N',
'sleep': 'V',
'furiously': 'ADV'
}

# Retrieving and displaying keys, values, and items from the 'pos' dictionary
print(list(pos.keys())) # Retrieve keys
print(list(pos.values())) # Retrieve values
print(list(pos.items())) # Retrieve key-value pairs
# Iterating through sorted key-value pairs and printing them
for key, val in sorted(pos.items()):
    print (key + ":", val)

pos['sleep'] = 'V'
pos['sleep']

pos['sleep'] = 'N'
pos['sleep']

pos = {'colorless': 'ADJ', 'ideas': 'N', 'sleep': 'V', 'furiously': 'ADV'}
pos = dict(colorless='ADJ', ideas='N', sleep='V', furiously='ADV')
from collections import defaultdict
frequency = defaultdict(int)
frequency['colorless'] = 4
frequency['ideas'] # Accessing a key that doesn't exist defaults to 0

from collections import defaultdict
pos = defaultdict(list)
pos ['sleep'] = ['NOUN', 'VERB']
pos['ideas'] # Accessing a key that doesn't exist defaults to an empty list
# Output: [ ]

from collections import defaultdict
pos = defaultdict(lambda: 'NOUN') # [1]
pos['colorless'] = 'ADJ'
pos['blog'] # [2]
# Output: 'NOUN'

list(pos.items())

import nltk
from collections import defaultdict
nltk.download('gutenberg') # Download the gutenberg corpus
# Load the text and create a frequency distribution of words
alice = nltk.corpus.gutenberg.words('carroll-alice.txt')
vocab = nltk.FreqDist(alice)
# Select the 1000 most common words
v1000 = [word for (word, _) in vocab.most_common (1000)]
# Create a mapping dictionary to replace less common words with 'UNK'
mapping = defaultdict(lambda: 'UNK')
for v in v1000:
    mapping[v] = v
# Transform the original text, replacing less common words with 'UNK'
alice2 = [mapping[v] for v in alice]
# Display the initial 100 transformed words
print(alice2[:100])
# Determine the number of unique tokens after transformation
print(len(set(alice2)))

from collections import defaultdict
from nltk.corpus import brown
from operator import itemgetter
counts = defaultdict(int)
for (word, tag) in brown.tagged_words(categories='news', tagset='universal'):
    counts [tag] += 1
counts ['NOUN']
sorted(counts)
sorted (counts.items(), key=itemgetter(1), reverse=True)
[t for t, c in sorted(counts.items(), key=itemgetter(1), reverse=True)]

pair = ('NP', 8336)
pair[1]
itemgetter(1)(pair)

from collections import defaultdict
import nltk
nltk.download('words') # Download the 'words' corpus
last_letters = defaultdict(list)
words = nltk.corpus.words.words('en')
for word in words:
    key = word[-2:]
    last_letters [key].append (word)
last_letters['ly']
last_letters['zy']

from collections import defaultdict
import nltk
anagrams = defaultdict(list)
words = nltk.corpus.words.words('en')
for word in words:
    key =''.join(sorted(word))
    anagrams [key].append (word)
anagrams ['aeilnrt']

import nltk
words = nltk.corpus.words.words('en')
anagrams = nltk.Index((''.join(sorted(w)), w) for w in words)
anagrams ['aeilnrt']

from collections import defaultdict
import nltk
pos = defaultdict(lambda: defaultdict(int))
brown_news_tagged = brown.tagged_words (categories='news', tagset='universal')
for ((w1, t1), (w2, t2)) in nltk.bigrams (brown_news_tagged):
    pos[(t1, w2)][t2] += 1
pos [('DET', 'right')]

from collections import defaultdict
import nltk
counts = defaultdict(int)
for word in nltk.corpus.gutenberg.words('milton-paradise.txt'):
    counts [word] += 1
[word for (word, count) in counts.items() if count == 32]
# Output: ['brought', 'Him', 'virtue', 'Against', 'There', 'thine', 'King', 'mortal', 'every', 'been']

pos = {'colorless': 'ADJ', 'ideas': 'N', 'sleep': 'V', 'furiously': 'ADV'}
pos2 = dict((value, key) for (key, value) in pos.items())
pos2['N']
# Output: 'ideas'

from collections import defaultdict
# NLP_LAB5.ipynb - Colaboratory
pos = {'colorless': 'ADJ', 'ideas': 'N', 'sleep': 'V', 'furiously': 'ADV'}
pos.update({'cats': 'N', 'scratch': 'V', 'peacefully': 'ADV','old': 'ADJ'})
pos2 = defaultdict(list)
for key, value in pos.items():
    pos2[value].append(key)
pos2['ADV'];

import nltk
pos = {'colorless': 'ADJ', 'ideas': 'N', 'sleep': 'V', 'furiously': 'ADV'}
pos.update({'cats': 'N', 'scratch': 'V', 'peacefully': 'ADV', 'old': 'ADJ'})
pos2 = nltk.Index((value, key) for (key, value) in pos.items())
pos2['ADV']
# Output: ['peacefully', 'furiously']

from nltk.corpus import brown
#Fetching tagged sentences from the 'news' category in the Brown corpus
brown_tagged_sents = brown.tagged_sents (categories='news')
# Fetching untagged sentences from the 'news' category in the Brown corpus
brown_sents = brown.sents(categories='news')
tags = [tag for (word, tag) in brown.tagged_words (categories='news')]
nltk.FreqDist (tags).max()

raw = 'I do not like green eggs and ham, I do not like them Sam I am!'
tokens = nltk.word_tokenize(raw)
default_tagger = nltk.DefaultTagger('NN')
default_tagger.tag (tokens)

default_tagger.evaluate(brown_tagged_sents)

patterns = [
(r'.*ing$', 'VBG'), # gerunds
# simple past
# 3rd singular present
# modals
(r'.*ed$', 'VBD'),
(r'.*es$', 'VBZ'),
(r'.*ould$', 'MD'),
(r'.*\'s$', 'NN$'),
(r'.*s$', 'NNS'),
(r'^-?[0-9]+(\.[0-9]+)?$', 'CD'), # cardinal numbers
(r'.*', 'NN') # nouns (default)
# possessive nouns
# plural nouns
]
regexp_tagger = nltk.RegexpTagger (patterns)
regexp_tagger.tag(brown_sents [3])

regexp_tagger.evaluate (brown_tagged_sents)

import nltk
fd = nltk.FreqDist(brown.words (categories='news'))
cfd = nltk.ConditionalFreqDist(brown.tagged_words (categories='news'))
most_freq_words = fd.most_common (100)
likely_tags = dict((word, cfd[word].max()) for (word, _) in most_freq_words)
baseline_tagger = nltk.UnigramTagger (model=likely_tags)
baseline_tagger.evaluate(brown_tagged_sents)

import nltk
sent = brown.sents (categories='news') [3]
baseline_tagger.tag(sent)

import nltk
baseline_tagger = nltk.UnigramTagger (model=likely_tags, backoff=nltk.DefaultTagger('NN'))
def performance(cfd, wordlist):
    lt = dict((word, cfd[word].max()) for word in wordlist)
    baseline_tagger = nltk.UnigramTagger (model=lt, backoff=nltk.DefaultTagger('NN'))
    return baseline_tagger.accuracy(brown.tagged_sents (categories='news')) # Changed evaluate() to accuracy()
def display():
    import pylab
    word_freqs = nltk.FreqDist(brown.words (categories='news')).most_common()
    words_by_freq = [w for (w, _) in word_freqs]
    cfd = nltk.ConditionalFreqDist(brown.tagged_words (categories='news'))
    sizes = 2 ** pylab.arange(15)
    perfs = [performance(cfd, words_by_freq[:size]) for size in sizes]
    pylab.plot(sizes, perfs, '-bo')
    pylab.title('Lookup Tagger Performance with Varying Model Size')
    pylab.xlabel('Model Size')
    pylab.ylabel('Performance')
    pylab.show()
display()

from nltk.corpus import brown
brown_tagged_sents = brown.tagged_sents (categories='news')
brown_sents = brown.sents(categories='news')
unigram_tagger = nltk.UnigramTagger (brown_tagged_sents)
unigram_tagger.tag(brown_sents [2007])

unigram_tagger.evaluate(brown_tagged_sents)

size = int(len(brown_tagged_sents) * 0.9)
train_sents = brown_tagged_sents[:size]
test_sents = brown_tagged_sents[size:]
unigram_tagger = nltk.UnigramTagger(train_sents)
unigram_tagger.evaluate(test_sents)

bigram_tagger = nltk.BigramTagger(train_sents)
bigram_tagger.tag(brown_sents [2007])

unseen_sent = brown_sents [4203]
bigram_tagger.tag(unseen_sent)

bigram_tagger.evaluate(test_sents)

t0 = nltk.DefaultTagger('NN')
t1 = nltk.UnigramTagger(train_sents, backoff=t0)
t2 = nltk.BigramTagger(train_sents, backoff=t1)
t2.evaluate(test_sents)

from pickle import dump
output = open('t2.pkl', 'wb')
dump(t2, output, -1)
output.close()
from pickle import load
input_file = open('t2.pkl', 'rb')
tagger = load(input_file)
input_file.close()
text = """The board's action shows what free enterprise
is up against in our complex maze of regulatory laws."""
tokens = text.split()
tagger.tag(tokens)

cfd = nltk.ConditionalFreqDist(
((x[1], y[1], z[0]), z[1])
for sent in brown_tagged_sents
for x, y, z in nltk.trigrams(sent))
ambiguous_contexts = [c for c in cfd.conditions() if len(cfd[c]) > 1]
sum(cfd[c].N() for c in ambiguous_contexts) / cfd.N()

test_tags = [tag for sent in brown.sents(categories='editorial')
for (word, tag) in t2.tag(sent)]
gold_tags = [tag for (word, tag) in brown.tagged_words(categories='editorial')]
print(nltk.ConfusionMatrix(gold_tags, test_tags))

from nltk.tbl import demo as brill_demo
brill_demo.demo()