# -*- coding: utf-8 -*-
"""NLP-LAB-2-Program

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GXa5_AwvAH9vsm06vEjoB61Wc4_kWdWT
"""

pip install spacy

import spacy
nlp = spacy.load("en_core_web_sm")
nlp

introduction_doc = nlp("This tutorial is about Natural Language Processing in")
type(introduction_doc)

[token.text for token in introduction_doc]

import pathlib
file_name = "Introduction.txt.txt"
introduction_doc = nlp(pathlib.Path(file_name).read_text(encoding="utf-8"))
print ([token.text for token in introduction_doc])

"""Sentence Detection"""

about_text = """Gus Proto is a Python developer currently working for a London-based Fintech company. He is interested in Natural Language Processing."""

about_doc = nlp(about_text)
sentences = list(about_doc.sents)
len(sentences)

for sentence in sentences:
    print(f"{sentence[:5]}...")

ellipsis_text = """Gus, can you, ... never mind, I forgot ... what I was saying. So, do you think we should ..."""

from spacy.language import Language
@Language.component("set_custom_boundaries")
def set_custom_boundaries (doc):
    for token in doc[:-1]:
        if token.text == "...":
            doc [token.i + 1].is_sent_start = True
    return doc
custom_nlp = spacy.load("en_core_web_sm")
custom_nlp.add_pipe("set_custom_boundaries", before="parser")

custom_ellipsis_doc = custom_nlp(ellipsis_text)
custom_ellipsis_sentences = list(custom_ellipsis_doc.sents)
custom_ellipsis_sentences = list(custom_ellipsis_doc.sents)
for sentence in custom_ellipsis_sentences:
    print(sentence)

"""Tokens in spaCy"""

import spacy
nlp = spacy.load("en_core_web_sm")
about_text = (
"Gus Proto is a Python developer currently"
" working for a London-based Fintech"
" company. He is interested in learning"
" Natural Language Processing."
)
about_doc = nlp(about_text)
for token in about_doc:
    print (token, token.idx)

print(
f'{"Text with Whitespace":22}'
f'{"Is Alphanumeric?":15}'
f'{"Is Punctuation?":18}'
f'{"Is Stop Word?"}')

for token in about_doc:
    print(
    f'{str(token.text_with_ws):22}'
    f'{str(token.is_alpha):15}'
    f'{str(token.is_punct):18}'
    f'{str(token.is_stop)}'
    )

custom_about_text = (
"Gus Proto is a Python developer currently"
" working for a London-based Fintech"
" company. He is interested in learning"
" Natural Language Processing."
)
tokens_to_print = [token.text for token in about_doc[8:15]]
print(tokens_to_print)

import re
import spacy
from spacy.tokenizer import Tokenizer
custom_nlp = spacy.load("en_core_web_sm")
prefix_re = spacy.util.compile_prefix_regex(custom_nlp.Defaults.prefixes)
suffix_re = spacy.util.compile_suffix_regex(custom_nlp.Defaults.suffixes)
custom_infixes = [r"@"]
infix_re = spacy.util.compile_infix_regex(
    list(custom_nlp.Defaults.infixes) + custom_infixes
)
custom_nlp.tokenizer = Tokenizer(
    custom_nlp.vocab,
    prefix_search=prefix_re.search,
    suffix_search=suffix_re.search,
    infix_finditer=infix_re.finditer,
    token_match=None,
)
custom_about_text = (
    "Gus Proto is a Python developer currently"
    " working for a London@based Fintech"
    " company. He is interested in learning"
    " Natural Language Processing."
)
custom_tokenizer_about_doc = custom_nlp(custom_about_text)
print([token.text for token in custom_tokenizer_about_doc[8:15]])

"""Stop Words"""

import spacy
spacy_stopwords = spacy.lang.en.stop_words.STOP_WORDS
len(spacy_stopwords)
for stop_word in list(spacy_stopwords)[:10]:
    print(stop_word)

import spacy
custom_about_text = (
"Gus Proto is a Python developer currently"
" working for a London-based Fintech"
" company. He is interested in learning"
" Natural Language Processing."
)
nlp = spacy.load("en_core_web_sm")
about_doc = nlp(custom_about_text)
filtered_tokens = [token.text for token in about_doc if not token.is_stop]
print(filtered_tokens)

"""Lemmatization"""

import spacy
nlp = spacy.load("en_core_web_sm")
conference_help_text = (
    "Gus is helping organize a developer"
    " conference on Applications of Natural Language"
    "Processing. He keeps organizing local Python meetups"
    " and several internal talks at his workplace."
)
conference_help_doc = nlp(conference_help_text)
for token in conference_help_doc:
    if str(token) != str(token.lemma_):
        print(f"{str(token):>20} : {str(token.lemma_)}")

"""Word Frequency"""

import spacy
from collections import Counter
nlp = spacy.load("en_core_web_sm")
complete_text = """Gus Proto is a Python developer currently working for a London-based Fintech company. He is interested in learning Natural Language Processing.
There is a developer conference happening on 21 July 2019 in London. It is titled "Applications of Natural Language Processing". There is a helpline number available at +44-1234567891. Gus is helping organize it.
He keeps organizing local Python meetups and several internal talks at his workplace. Gus is also presenting a talk. The talk will introduce the reader about "Use cases of Natural Language Processing in Fintech".
Apart from his work, he is very passionate about music. Gus is learning to play the Piano. He has enrolled himself in the weekend batch of Great Piano Academy.
Great Piano Academy is situated in Mayfair or the City of London and has world-class piano instructors."""
complete_doc = nlp(complete_text)
words = [
    token.text
    for token in complete_doc
    if not token.is_stop and not token.is_punct
]
print(Counter(words).most_common(5))

Counter(
[token.text for token in complete_doc if not token.is_punct]
).most_common(5)

"""Part-of-Speech Tagging"""

import spacy
nlp = spacy.load("en_core_web_sm")
about_text = (
    "Gus Proto is a Python developer currently"
    " working for a London-based Fintech"
    " company. He is interested in learning" # Added missing opening quote
    " Natural Language Processing."
)
about_doc = nlp(about_text)
for token in about_doc:
    print(
        f"""TOKEN: {str(token)}
TAG: {str(token.tag_):10} POS: {token.pos_}
EXPLANATION: {spacy.explain(token.tag_)}"""
    )

nouns = []
adjectives = []
for token in about_doc:
    if token.pos_ == "NOUN":
        nouns.append(token)
    if token.pos_ == "ADJ":
        adjectives.append(token)

nouns

adjectives

"""Visualization: Using displaCy"""

import spacy
from spacy import displacy
nlp = spacy.load("en_core_web_sm")
about_interest_text = "He is interested in learning Natural Language Processing"
about_interest_doc = nlp(about_interest_text)
# Generate HTML code for the dependency parse tree
html_code = displacy.render(about_interest_doc, style="dep", options={"distance": 120})
# Print or save the HTML code as needed
print(html_code)

"""Preprocessing Functions"""

import spacy
nlp = spacy.load("en_core_web_sm")
complete_text = """Gus Proto is a Python developer currently
working for a London-based Fintech company. He is
interested in learning Natural Language Processing.
There is a developer conference happening on 21 July
2019 in London. It is titled "Applications of Natural
Language Processing". There is a helpline number
available at +44-1234567891. Gus is helping organize it.
He keeps organizing local Python meetups and several
internal talks at his workplace. Gus is also presenting
a talk. The talk will introduce the reader about "Use
cases of Natural Language Processing in Fintech".
Apart from his work, he is very passionate about music.
Gus is learning to play the Piano. He has enrolled
himself in the weekend batch of Great Piano Academy.
Great Piano Academy is situated in Mayfair or the City
of London and has world-class piano instructors."""
complete_doc = nlp(complete_text)
def is_token_allowed(token):
    return bool(
        token
        and str(token).strip()
        and not token.is_stop
        and not token.is_punct
    )
def preprocess_token(token):
    return token.lemma_.strip().lower()
complete_filtered_tokens = [
    preprocess_token(token)
    for token in complete_doc
    if is_token_allowed(token)
]
print(complete_filtered_tokens)

"""Rule-Based Matching Using spaCy"""

import spacy
nlp = spacy.load("en_core_web_sm")
about_text = (
    "Gus Proto is a Python developer currently"
    " working for a London-based Fintech"
    " company. He is interested in learning"
    " Natural Language Processing."
)
about_doc = nlp(about_text)
from spacy.matcher import Matcher
matcher = Matcher(nlp.vocab)
def extract_full_name(nlp_doc):
    pattern = [{"POS": "PROPN"}, {"POS": "PROPN"}]
    matcher.add("FULL_NAME", [pattern])
    matches = matcher(nlp_doc)
    for _,start, end in matches:
        span = nlp_doc[start:end]
        yield span.text
# Print the extracted full name
print(next(extract_full_name(about_doc)))

"""Dependency Parsing Using spaCy"""

import spacy
nlp = spacy.load("en_core_web_sm")
one_line_about_text = (
"Gus Proto is a Python developer"
" currently working for a London-based Fintech company"
)
one_line_about_doc = nlp(one_line_about_text)
# Extract children of `developer
print([token.text for token in one_line_about_doc[5].children])
# Extract previous neighboring node of `developer
print(one_line_about_doc[5].nbor(-1))
# Extract next neighboring node of ` developer
print(one_line_about_doc[5].nbor())
# Extract all tokens on the left of `developer
print([token.text for token in one_line_about_doc[5].lefts])
# Extract tokens on the right of `developer
print([token.text for token in one_line_about_doc[5].rights])
# Print subtree of`developer
print(list(one_line_about_doc[5].subtree))

import spacy
nlp = spacy.load("en_core_web_sm")
piano_text = "Gus is learning piano"
piano_doc = nlp(piano_text)
for token in piano_doc:
    print(
        f"""
TOKEN: {token.text}
{token.tag_ =}
{token.head.text =}
{token.dep_ =}"""
    )

displacy.serve(piano_doc, style="dep")

import spacy

nlp = spacy.load("en_core_web_sm")
one_line_about_text = (
"Gus Proto is a Python developer"
" currently working for a London-based Fintech company"
)
one_line_about_doc = nlp(one_line_about_text)
# Extract children of `developer
print([token.text for token in one_line_about_doc[5].children])
# Extract previous neighboring node of `developer
print(one_line_about_doc[5].nbor(-1))
# Extract next neighboring node of ` developer
print(one_line_about_doc[5].nbor())
# Extract all tokens on the left of `developer
print([token.text for token in one_line_about_doc[5].lefts])
# Extract tokens on the right of `developer
print([token.text for token in one_line_about_doc[5].rights])
# Print subtree of`developer
print(list(one_line_about_doc[5].subtree))

"""Named-Entity Recognition"""

import spacy
nlp = spacy.load("en_core_web_sm")
piano_class_text = (
    "Great Piano Academy is situated"
    " in Mayfair or the City of London and has"
    "world-class piano instructors."
)
piano_class_doc = nlp(piano_class_text)
for ent in piano_class_doc.ents:
    print(
        f"""
{ent.text =}
{ent.start_char =}
{ent.end_char =}
{ent.label_ =}
spacy.explain('{ent.label_}') = {spacy.explain(ent.label_)}"""
    )

displacy.serve(piano_class_doc, style="ent")

survey_text = """Out of 5 people surveyed, James Robert,
Julie Fuller and Benjamin Brooks like
apples. Kelly Cox and Matthew Evans
like oranges."""
def replace_person_names(token):
    if token.ent_iob != 0 and token.ent_type_ == "PERSON":
        return "[REDACTED] "
    return token.text_with_ws
def redact_names(nlp_doc):
    with nlp_doc.retokenize() as retokenizer:
        for ent in nlp_doc.ents:
            retokenizer.merge(ent)
        tokens = map(replace_person_names, nlp_doc)
        return "".join(tokens)
survey_doc = nlp(survey_text)
print(redact_names(survey_doc))