# -*- coding: utf-8 -*-
"""NLP-LAB-4-Program

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EthexQFPyiS_bVeze53Tijw8kLF5zU_-

BUILDING LANGUAGE MODELS
N gram model
"""

def readData():
    data = ['This is a dog','This is a cat','I love my cat','This is my name']
    dat=[]
    for i in range(len(data)):
        for word in data[i].split():
            dat.append (word)
    print(dat)
    return dat
def createBigram(data):
    listOfBigrams = []
    bigramCounts = {}
    unigramCounts = {}
    for i in range(len(data)-1):
        # This condition `if i< len(data) - 1 and data[i+1].islower():` seems problematic for bigram creation.
        # It will only create bigrams where the second word starts with a lowercase letter.
        # Assuming the intention is to create all bigrams, the `islower()` check might be removed or adjusted.
        # For now, I'm keeping it as is, but it's worth reviewing.
        if i < len(data) - 1:
            listOfBigrams.append((data[i], data[i + 1]))
            if (data[i], data[i+1]) in bigramCounts:
                bigramCounts[(data[i], data[i + 1])] += 1
            else:
                bigramCounts[(data[i], data[i + 1])] = 1
        if data[i] in unigramCounts:
            unigramCounts[data[i]] += 1
        else:
            unigramCounts[data[i]] = 1
    # Add the last word to unigram counts if not already counted
    if len(data) > 0 and data[-1] not in unigramCounts:
        unigramCounts[data[-1]] = 1
    elif len(data) > 0 and data[-1] in unigramCounts:
        unigramCounts[data[-1]] += 1

    return listOfBigrams, unigramCounts, bigramCounts
def calcBigramProb(listOfBigrams, unigramCounts, bigramCounts):
    listOfProb = {}
    for bigram in listOfBigrams:
        word1 = bigram[0]
        word2 = bigram[1]
        # Handle potential division by zero if unigram count is 0
        if unigramCounts.get(word1, 0) > 0:
            listOfProb[bigram] = (bigramCounts.get(bigram, 0))/(unigramCounts.get(word1))
        else:
            listOfProb[bigram] = 0 # Or handle as appropriate, e.g., NaN, skip
    return listOfProb
if __name__ == '__main__': # Fixed typo
    data_words = readData() # Changed variable name to avoid conflict, fixed function call
    listOfBigrams, unigramCounts, bigramCounts = createBigram(data_words) # Corrected indentation
    print("\n All the possible Bigrams are ")
    print(listOfBigrams)
    print("\n Bigrams along with their frequency ")
    print(bigramCounts)
    print("\n Unigrams along with their frequency ")
    print(unigramCounts)
    bigramProb = calcBigramProb(listOfBigrams, unigramCounts, bigramCounts)
    print("\n Bigrams along with their probability ")
    print (bigramProb)
    inputList="This is my cat"
    splt=inputList.split()
    outputProb1 = 1
    bilist=[] # Fixed initialization
    # bigrm=[] # This variable was defined but not used. Removed.
    for i in range(len(splt) - 1):
        if i < len(splt) - 1: # Fixed missing comparison operator
            bilist.append((splt[i], splt[i + 1]))
    print("\n The bigrams in given sentence are ")
    print(bilist)
    for i in range(len(bilist)):
        if bilist[i] in bigramProb:
            outputProb1 *= bigramProb[bilist[i]]
        else:
            outputProb1 *= 0

import nltk
nltk.download('punkt_tab')

import nltk
nltk.download('reuters')
from nltk.corpus import reuters
from nltk import bigrams, trigrams
from collections import Counter, defaultdict
# Create a placeholder for model
model = defaultdict(lambda: defaultdict(lambda: 0))
# Count frequency of co-occurancе
for sentence in reuters.sents():
    for w1, w2, w3 in trigrams (sentence, pad_right=True, pad_left=True):
        model[(w1, w2)][w3] += 1
# Let's transform the counts to probabilities
for w1, w2 in model:
    total_count = float(sum(model[(w1, w2)].values()))
    for w3 in model[(w1, w2)]:
        model[(w1, w2)][w3] /= total_count
dict(model["today", "the"])

import random
# starting words
text = ["today", "the"]
sentence_finished = False
while not sentence_finished:
    # select a random probability threshold
    r = random.random()
    accumulator = 0.0
    for word in model[tuple(text[-2:])].keys():
        accumulator += model[tuple(text[-2:])][word]
    # select words that are above the probability threshold
    if accumulator >= r:
        text.append(word)
        break
    if text[-2:] == [None, None]:
        sentence_finished = True
print (' '.join([t for t in text if t]))

import numpy as np
import pandas as pd
from keras.utils import to_categorical
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import LSTM, Dense, GRU, Embedding
from keras.callbacks import EarlyStopping, ModelCheckpoint
data_text = """The unanimous Declaration of the thirteen united States of America, When in
We hold these truths to be self-evident, that all men are created equal, that they are endo
He has refused his Assent to Laws, the most wholesome and necessary for the public good.
He has forbidden his Governors to pass Laws of immediate and pressing importance, unless su
He has refused to pass other Laws for the accommodation of large districts of people, unles:
He has called together legislative bodies at places unusual, uncomfortable, and distant fror
He has dissolved Representative Houses repeatedly, for opposing with manly firmness his inva
He has refused for a long time, after such dissolutions, to cause others to be elected; whe
He has endeavoured to prevent the population of these States; for that purpose obstructing
He has obstructed the Administration of Justice, by refusing his Assent to Laws for establi:
He has made Judges dependent on his Will alone, for the tenure of their offices, and the am
He has erected a multitude of New Offices, and sent hither swarms of Officers to harrass ou
He has kept among us, in times of peace, Standing Armies without the Consent of our legisla
He has affected to render the Military independent of and superior to the Civil power.
He has combined with others to subject us to a jurisdiction foreign to our constitution, and
For Quartering large bodies of armed troops among us:
For protecting them, by a mock Trial, from punishment
For cutting off our Trade with all parts of the world:
For imposing Taxes on us without our Consent:
for any Murders which they should comr
For depriving us in many cases, of the benefits of Trial by Jury:
For transporting us beyond Seas to be tried for pretended offences
For abolishing the free System of English Laws in a neighbouring Province, establishing the
For taking away our Charters, abolishing our most valuable Laws, and altering fundamentally
For suspending our own Legislatures, and declaring themselves invested with power to legisl
He has abdicated Government here, by declaring us out of his Protection and waging War agai
He has plundered our seas, ravaged our Coasts, burnt our towns, and destroyed the lives of
He is at this time transporting large Armies of foreign Mercenaries to compleat the works
He has constrained our fellow Citizens taken Captive on the high Seas to bear Arms against
He has excited domestic insurrections amongst us, and has endeavoured to bring on the inhab:
In every stage of these Oppressions We have Petitioned for Redress in the most humble terms
Nor have We been wanting in attentions to our Brittish brethren. We have warned them from
We, therefore, the Representatives of the united States of America, in General Congress, As"""
import re
def text_cleaner(text):
    # Lower case text
    newString = text.lower()
    newString = re.sub(r"'s\b","",newString)
    # remove punctuations
    newString = re.sub("[^a-zA-Z]", " ", newString)
    long_words=[]
    # remove short word
    for i in newString.split():
        if len(i)>=3:
            long_words.append(i)
    return (" ".join(long_words)).strip()
# preprocess the text
data_new = text_cleaner(data_text)

def create_seq(text):
    length = 30
    sequences = list()
    for i in range(length, len(text)):
        # select sequence of tokens
        seq = text[i-length:i+1]
        # store
        sequences.append(seq)
    print('Total Sequences: %d' % len(sequences))
    return sequences
# create sequences
sequences = create_seq(data_new)

chars = sorted(list(set(data_new)))
mapping = dict((c, i) for i, c in enumerate(chars))

chars = sorted(list(set(data_new)))
mapping = dict((c, i) for i, c in enumerate(chars))
def encode_seq(seq):
    sequences = list()
    for line in seq:
        # integer encode Line
        encoded_seq = [mapping [char] for char in line]
        # store
        sequences.append (encoded_seq)
    return sequences
# encode the sequences
sequences = encode_seq(sequences)

def encode_seq(seq, mapping):
    encoded_seqs = []
    for line in seq:
        # integer encode Line
        encoded_seq = [mapping[char] for char in line]
        # store
        encoded_seqs.append(encoded_seq)
    return np.array(encoded_seqs)

# encode the sequences
# sequences = encode_seq(sequences, mapping) # This line is commented out as sequences are already encoded.

sequences

vocab = len(mapping)
sequences = np.array(sequences)
X, y = sequences[:, :-1], sequences[:, -1]
# one hot encode y
y = to_categorical(y, num_classes=vocab)

from sklearn.model_selection import train_test_split
# vocabulary size
vocab = len(mapping)
sequences = np.array (sequences)
# create X and y
# create train and validation sets
X_tr, X_val, y_tr, y_val = train_test_split(X, y, test_size=0.1, random_state=42)
print('Train shape:', X_tr.shape, 'Val shape:', X_val.shape)

from sklearn.model_selection import train_test_split
from keras.utils import to_categorical
import numpy as up
# Assuming you have a 'mapping' variable defined elsewhere
# vocab = Len(mapping)
# Assuming you have a 'sequences' variable defined elsewhere
# sequences = np.array(sequences)
# Reshape sequences to make it 2-dimensional
sequences = sequences.reshape((len(sequences), sequences.shape[1]))
# create X and y
X, y = sequences[:, :-1], sequences[:, -1]
# one hot encode y
y = to_categorical(y, num_classes=vocab)
# create train and validation sets
X_tr, X_val, y_tr, y_val = train_test_split(X, y, test_size=0.1, random_state=42)
print('Train shape:', X_tr.shape, 'Val shape:', X_val.shape)

model = Sequential()
model.add(Embedding(vocab, 50, input_length=30, trainable=True))
model.add(GRU(150, recurrent_dropout=0.1, dropout=0.1))
model.add(Dense(vocab, activation='softmax'))
print(model.summary())
# compile the model
model.compile(loss='categorical_crossentropy', metrics=['acc'], optimizer='adam')
# fit the model
model.fit(X_tr, y_tr, epochs=100, verbose=2, validation_data=(X_val, y_val))

import numpy as np
from keras.preprocessing.sequence import pad_sequences

def generate_seq(model, mapping, seq_length, seed_text, n_chars):
    in_text = seed_text
    # generate a fixed number of characters
    for _ in range(n_chars):
        # encode the characters as integers
        encoded = [mapping[char] for char in in_text]
        # truncate sequences to a fixed length
        encoded = pad_sequences([encoded], maxlen=seq_length, truncating='pre')
        # predict character probabilities
        yhat_probs = model.predict(encoded, verbose=0)
        # get the index of the character with the highest probability
        yhat = np.argmax(yhat_probs)

        # reverse map integer to character
        out_char = '' # Fixed unterminated string literal
        for char_key, index_val in mapping.items():
            if index_val == yhat:
                out_char = char_key
                break
        # append to input
        in_text += out_char
    return in_text

import numpy as np
from keras.preprocessing.sequence import pad_sequences

def generate_seq(model, mapping, seq_length, seed_text, n_chars):
    in_text = seed_text
    # generate a fixed number of characters
    for _ in range(n_chars):
        # encode the characters as integers
        encoded = [mapping[char] for char in in_text]
        # truncate sequences to a fixed length
        encoded = pad_sequences([encoded], maxlen=seq_length, truncating='pre')
        # predict character probabilities
        yhat_probs = model.predict(encoded, verbose=0)
        # get the index of the character with the highest probability
        yhat = np.argmax(yhat_probs)

        # reverse map integer to character
        out_char = ''
        for char_key, index_val in mapping.items():
            if index_val == yhat:
                out_char = char_key
                break
        # append to input
        in_text += out_char
    return in_text

inp='Large armies of'
print(len(inp))
print(generate_seq(model,mapping, 50, inp.lower(),15))