# -*- coding: utf-8 -*-
"""NLP-LAB-3-Program

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gu-Hzg17_GELyyb-GfwpclamwSiiz39D

One-Hot Encoding
"""

import numpy as np
# Step 1: Convert Text to Lower case
text = "My Name is AKilesh"
text_lower = text.lower()
# Step 2: Tokenize the text
tokens = text_lower.split()
# Step 3: Get unique words
unique_words = set (tokens)
# Step 4: Sort the word List
sorted_words = sorted(unique_words)
# Step 5: Get the integer/position of the words
word_to_index = {word: index for index, word in enumerate(sorted_words)}
# Step 6 and 7: Create one-hot vectors and matrix
one_hot_matrix = np.zeros((len(tokens), len(unique_words)))
for i, token in enumerate(tokens):
    word_index = word_to_index[token]
    one_hot_matrix[i, word_index] = 1
# Display the results
print("Original Text:", text)
print("One-Hot Matrix:")
print(one_hot_matrix)

"""Bag of Words"""

from sklearn.feature_extraction.text import CountVectorizer
# Example Sentences
sentence1 = "My Name is AKilesh"
sentence2 = "I am a student at AVV chennai"
# Step 1: Convert to Lowercase
sentence1 = sentence1.lower()
sentence2 = sentence2.lower()
#
#
# Step 2: Remove special characters and stopwords (optional)
# In this example, we'll skip this step for simplicity.
# Step 3: Create a list of sentences
corpus = [sentence1, sentence2]
# Step 4: Use CountVectorizer to create Bag of Words model
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
# Display the vocabulary and the Bag of Words matrix
print("Vocabulary:", vectorizer.get_feature_names_out())
print("Bag of Words Matrix:")
print(X.toarray())

import pandas as pd
import numpy as nd
# Construct a small corpus
corpus = ['data science is one of the most important fields of science',
'this is one of the best data science courses',
'data scientists analyze data']
# Create a word set for the corpus
words_set = set()
for doc in corpus:
    words = doc.split() # Fixed: Changed from split('') to split() for proper word tokenization
    words_set = words_set.union(set(words))
print('Number of words in the corpus:', len(words_set))
print('The words in the corpus:\n', words_set)
# Computing Term Frequency (TF)
n_docs = len(corpus)
n_words_set = len(words_set)
df_tf = pd.DataFrame(np.zeros((n_docs, n_words_set)), columns=list(words_set))
# Compute Term Frequency (TF)
for i in range(n_docs):
    words = corpus[i].split(' ') # Words in the document
    for w in words:
        df_tf.loc[i, w] = df_tf.loc[i, w] + (1 / len(words)) # Fixed: Using .loc to avoid ChainedAssignmentError
print("Term Frequency (TF):")
print(df_tf)
# Computing Inverse Document Frequency (IDF)
print("\nInverse Document Frequency (IDF):")
idf = {}
for w in words_set: # Fixed: Corrected typo from words _set to words_set
    k = 0 # number of documents in the corpus that contain this word
    for i in range(n_docs):
        if w in corpus[i].split():
            k += 1
    idf[w] = np.log10(n_docs / k)
    print(f'{w:>15}: {idf[w]:>10}.') # Fixed: Removed unclosed parenthesis
# Putting it Together: Computing TF-IDF
df_tf_idf = df_tf.copy()
for w in words_set:
    for i in range(n_docs):
        df_tf_idf.loc[i, w] = df_tf.loc[i, w] * idf[w] # Fixed: Using .loc to avoid ChainedAssignmentError
print("\nTF-IDF:")
print(df_tf_idf)
# Removed: 'localhost:8888/notebooks/Downloads/NLP' was not valid Python code

"""WORD2VEC"""

pip install gensim

import gensim
from gensim.models import KeyedVectors
import gensim.downloader as api
# DownLoad the pre-trained Word2Vec model from Google (takes some time)
# This downloads a large file, so be patient.
word2vec_model_path = api.load("word2vec-google-news-300", return_path=True)
# Load the Word2Vec model using gensim
word2vec_model = gensim.models.KeyedVectors.load_word2vec_format(word2vec_model_path, binary=True)
# Example: Get the word embedding for the word "king"
word_embedding = word2vec_model["king"]
# Print the dimensionality of the word embedding
print("Dimensionality of word embedding:", len(word_embedding))
# Example: Get the most similar words to "king"
similar_words = word2vec_model.most_similar("king")
print("Words most similar to 'king':", similar_words)
# Example: Calculate the similarity between two words
similarity_score = word2vec_model.similarity("king", "queen")
print("Similarity between 'king' and 'queen':", similarity_score)
# Example: Calculate the vector representing the combination of words "king" and "man" minus
result_vector = word2vec_model.most_similar(positive=["king", "man"], negative=["woman"], topn=1)
print("Vector representation of 'king- man + woman':", result_vector)

pip install spacy

!python -m spacy download en_core_web_md

"""GLOVE"""

import spacy
# Load the pre-trained GLoVe model
nlp = spacy.load("en_core_web_md")
# Test sentences
sentence1 = "I love natural language processing."
sentence2 = "GloVe is a powerful word embedding technique."
# Tokenize and get word embeddings for each sentence
doc1 = nlp(sentence1)
doc2 = nlp(sentence2) # Fixed: Changed n1p to nlp
# Print word embeddings for each word in the sentences
print("Word embeddings for sentence 1:")
for token in doc1:
    print(f"{token.text}: {token.vector}") # Fixed: IndentationError
print("\nWord embeddings for sentence 2:")
for token in doc2:
    print(f"{token.text}: {token.vector}") # Fixed: IndentationError

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np # Changed ud to np for consistency and correctness

# Define a list of strings as your sample text
x = ['text', 'the', 'leader', 'prime', 'natural', 'language']

# Create the tokenizer
tokenizer = Tokenizer()
tokenizer.fit_on_texts(x)

# Number of unique words in the dictionary
print("Number of unique words in the dictionary =", len(tokenizer.word_index))
print("Dictionary is =", tokenizer.word_index)

# Function to create an embedding matrix for the vocabulary
def embedding_for_vocab(filepath, word_index, embedding_dim):
    vocab_size = len(word_index) + 1  # Corrected indentation
    # Adding again 1 because of reserved 0 index
    embedding_matrix_vocab = np.zeros((vocab_size, embedding_dim))
    try:
        with open(filepath, encoding="utf8") as f:
            for line in f:
                word, *vector = line.split()
                if word in word_index: # Corrected 'word index' to 'word_index'
                    idx = word_index[word]
                    # Ensure the vector has enough elements before slicing
                    if len(vector) >= embedding_dim:
                        embedding_matrix_vocab[idx] = np.array(vector, dtype=np.float32)[:embedding_dim] # Corrected slicing and variable
                    else:
                        # Handle cases where vector is too short (e.g., fill with zeros or skip)
                        print(f"Warning: Vector for '{word}' is too short. Skipping or padding with zeros.")

    except FileNotFoundError:
        print(f"Error: GloVe file '{filepath}' not found. Please ensure it's in the correct directory.")
        # Return an empty matrix or handle the error as appropriate for your application
        return np.zeros((vocab_size, embedding_dim))

    return embedding_matrix_vocab

# Define the embedding dimension
embedding_dim = 100

# Generate the embedding matrix for the given GloVe file
# Note: This will likely fail unless 'glove.6B.100d.txt' is downloaded and in the correct path
embedding_matrix_vocab = embedding_for_vocab('glove.6B.100d.txt', tokenizer.word_index, embedding_dim) # Completed function call

# Print the dense vector for the first word in the vocabulary
# This assumes the embedding matrix was successfully created and populated
if embedding_matrix_vocab.shape[0] > 1:
    first_word_in_vocab = list(tokenizer.word_index.keys())[0]
    first_word_id = tokenizer.word_index[first_word_in_vocab]
    print(f"\nDense vector for '{first_word_in_vocab}':\n{embedding_matrix_vocab[first_word_id]}")
else:
    print("Embedding matrix is empty or not properly initialized.")

import spacy
import matplotlib.pyplot as plt
from sklearn.manifold import TSNE
import numpy as np # Changed 'up' to 'np'
# Load the pre-trained GloVe model
nlp = spacy.load("en_core_web_md")
# List of words for visualization
words_to_visualize = ["natural", "language", "processing", "GloVe", "powerful", "word", "embeddings"]
# Get word embeddings for the selected words
word_vectors = [nlp(word).vector for word in words_to_visualize]
# Convert word_vectors to a NumPy array
word_vectors_array = np.array(word_vectors)
# Ensure perplexity is less than the number of samples
perplexity = min(30, len(word_vectors_array) - 1)
# Apply t-SNE to reduce dimensionality to 2D
tsne = TSNE(n_components=2, perplexity=perplexity, random_state=42)
word_vectors_2d = tsne.fit_transform(word_vectors_array)
# Plot the words in 2D space
plt.figure(figsize=(8, 8))
plt.scatter(word_vectors_2d[:, 0], word_vectors_2d[:, 1])
# Annotate each point with the corresponding word
for i, word in enumerate(words_to_visualize):
    plt.annotate(word, (word_vectors_2d[i, 0], word_vectors_2d[i, 1])) # Fixed indentation
plt.title("t-SNE Visualization of Word Embeddings")
plt.show()

"""FAST TEXT"""

!pip install gensim
import nltk
from nltk.tokenize import word_tokenize
from gensim.models import FastText


# Download the 'punkt_tab' resource if not already downloaded
# This is necessary for word_tokenize to function correctly
try:
    nltk.data.find('tokenizers/punkt_tab')
except LookupError:
    nltk.download('punkt_tab')

# Dummy sentences
sentences = [
    "This is a sample sentence for FastText.",
    "FastText is a powerful word embedding model.",
    "We can train FastText on custom sentences too.",
    "Creating a simple example for demonstration.",
    "Let's check the similarity of some words."
]
# Tokenize the sentences
tokenized_sentences = [word_tokenize(sentence.lower()) for sentence in sentences]
# Train FastText model
model = FastText(
    sentences=tokenized_sentences,
    vector_size=128,
    window=5,
    min_count=1, # Adjust min_count as needed
    workers=4,
    epochs=10,
    sg=1,
    seed=42
)
# Save the trained model
model.save('dummy_fasttext_model')
# Access the word vectors
ftext = model.wv
# Check the number of unique words in the model
print("Number of unique words:", len(ftext.index_to_key))
# Check the vector size
print("Vector size:", ftext.vector_size)
# Get the vector for a specific word
word_vector = ftext["fasttext"]
print("Vector for 'fasttext':", word_vector)
# Find similar words
similar_words_mantap = ftext.similar_by_word("mantap", topn=5)
print("Similar words to 'mantap':", similar_words_mantap)
similar_words_bagus = ftext.similar_by_word("bagus", topn=5)
print("Similar words to 'bagus':", similar_words_bagus)